name: isekai
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: 5.4.4
  collection: 1.18.0
  cupertino_icons: 1.0.8
  faker: 2.2.0
  firebase_analytics: 11.3.3
  firebase_auth: 5.3.1
  firebase_core: 3.6.0
  firebase_crashlytics: 4.1.3
  firebase_remote_config: 5.1.3
  flame: 1.21.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  freezed_annotation: 2.4.4
  in_app_review: 2.0.9
  intl: 0.19.0
  package_info_plus: 8.1.0
  shared_preferences: 2.3.2

dev_dependencies:
  analyzer: 6.4.1
  build_runner: 2.4.13
  cider: 0.2.8
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  json_serializable: 6.8.0
  mocktail: 1.0.4
  pedantic_mono: 1.29.0
  test: 1.25.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/tiles/
